### PR TITLE
Randomize skin colors

### PR DESCRIPTION
**Pull request by haykam821**
This would make bots spawn with a random skin color, id `0` through `5`.

### CODE REVIEW

**Comment by Mega-Mewthree** [comment]
Make it a `--randskins` option.

**Comment by FirstPlayerNebula** [comment]
I did it without commands, just replace skins:0 to skins:Math.floor((Math.random() * 6) + 0)

**Comment by haykam821** [comment]
@FirstPlayerNebula The code was already added before your comment.

**Comment by Mega-Mewthree** [comment]
Change --randomSkins to --randskins please. Make it follow the same format as --randnames.

**Comment by haykam821** [comment]
I’ll do that, but it will be camelCase.

**Comment by Mega-Mewthree** [comment]
Also update the start.bat to add a randskins option.

**Pull request merged**
