### PR TITLE
Added Dual Probe option for more precise searches.

### PR DESCRIPTION
**Pull request by EuphoricPenguin**
This function isn't so much for finding servers to join, but for finding specific streamers, players, or finding an un-copied party link.

### CODE REVIEW

**Comment by Mega-Mewthree** [comment]
This actually gives you more IPs when you really want to narrow the search range.

**Comment by EuphoricPenguin** [comment]
I don't understand. I've always gotten the correct IP based on my use of this feature. It's the most useful Probe config for my use.

**Comment by haykam821** [comment]
So, basically this is `--probeTribe XXX --probeName YYY` in `start.bat`. This is not a problem in that file, but rather a problem in the Node.js code. If we switched from using `OR` when we search with both to `AND`, this would give us the ability to do more precise searches, which is what I would want, and what I think @Mega-Mewthree wants.

**Comment by Mega-Mewthree** [comment]
Someone add the AND option and I'll merge this.

**Comment by haykam821** [comment]
So basically `--probeLogicGate`? How about I add it to the yargs PR to force you to merge that ;)

**Comment by haykam821** [comment]
How about I add it to the yargs PR to force you to merge that ;)

**Pull request closed without merging**
